services:
  - type: web
    name: ocr-app
    env: python
    runtime: python-3.10.12
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
  